// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hosts.sql

package sqlc

import (
	"context"
	"time"
)

const allHosts = `-- name: AllHosts :many
SELECT id, host_name, canonical_name, url, ip, ipv6, location, os, active, created_at, updated_at 
FROM hosts 
ORDER BY host_name
`

func (q *Queries) AllHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, allHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.HostName,
			&i.CanonicalName,
			&i.Url,
			&i.Ip,
			&i.Ipv6,
			&i.Location,
			&i.Os,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, event_type, host_service_id, host_id, service_name, host_name, message, created_at, updated_at 
FROM events 
ORDER BY created_at
`

func (q *Queries) GetAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.HostServiceID,
			&i.HostID,
			&i.ServiceName,
			&i.HostName,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllServiceStatusCounts = `-- name: GetAllServiceStatusCounts :one
SELECT 
    (SELECT COUNT(id) FROM host_services WHERE active = 1 AND status = 'pending') as pending,
    (SELECT COUNT(id) FROM host_services WHERE active = 1 AND status = 'healthy') as healthy,
    (SELECT COUNT(id) FROM host_services WHERE active = 1 AND status = 'warning') as warning,
    (SELECT COUNT(id) FROM host_services WHERE active = 1 AND status = 'problem') as problem
`

type GetAllServiceStatusCountsRow struct {
	Pending int64
	Healthy int64
	Warning int64
	Problem int64
}

func (q *Queries) GetAllServiceStatusCounts(ctx context.Context) (GetAllServiceStatusCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getAllServiceStatusCounts)
	var i GetAllServiceStatusCountsRow
	err := row.Scan(
		&i.Pending,
		&i.Healthy,
		&i.Warning,
		&i.Problem,
	)
	return i, err
}

const getHostByID = `-- name: GetHostByID :one
SELECT id, host_name, canonical_name, url, ip, ipv6, location, os, active, created_at, updated_at
FROM hosts
WHERE id = $1
`

func (q *Queries) GetHostByID(ctx context.Context, id int32) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.HostName,
		&i.CanonicalName,
		&i.Url,
		&i.Ip,
		&i.Ipv6,
		&i.Location,
		&i.Os,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostServiceByHostIDServiceID = `-- name: GetHostServiceByHostIDServiceID :one
SELECT 
    hs.id, hs.host_id, hs.service_id, hs.active, hs.schedule_number,
    hs.schedule_unit, hs.last_check, hs.status, hs.created_at, hs.updated_at,
    COALESCE(s.id, 0) as service_id_ref, 
    COALESCE(s.service_name, '') as service_name, 
    COALESCE(s.active, 0) as service_active, 
    COALESCE(s.icon, '') as icon, 
    COALESCE(s.created_at, hs.created_at) as service_created_at, 
    COALESCE(s.updated_at, hs.updated_at) as service_updated_at, 
    COALESCE(h.host_name, '') as host_name, 
    hs.last_message
FROM host_services hs
LEFT JOIN services s ON (hs.service_id = s.id)
LEFT JOIN hosts h ON (hs.host_id = h.id)
WHERE hs.host_id = $1 AND hs.service_id = $2
`

type GetHostServiceByHostIDServiceIDParams struct {
	HostID    int32
	ServiceID int32
}

type GetHostServiceByHostIDServiceIDRow struct {
	ID               int32
	HostID           int32
	ServiceID        int32
	Active           int32
	ScheduleNumber   int32
	ScheduleUnit     string
	LastCheck        time.Time
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ServiceIDRef     int32
	ServiceName      string
	ServiceActive    int32
	Icon             string
	ServiceCreatedAt time.Time
	ServiceUpdatedAt time.Time
	HostName         string
	LastMessage      string
}

func (q *Queries) GetHostServiceByHostIDServiceID(ctx context.Context, arg GetHostServiceByHostIDServiceIDParams) (GetHostServiceByHostIDServiceIDRow, error) {
	row := q.db.QueryRowContext(ctx, getHostServiceByHostIDServiceID, arg.HostID, arg.ServiceID)
	var i GetHostServiceByHostIDServiceIDRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ServiceID,
		&i.Active,
		&i.ScheduleNumber,
		&i.ScheduleUnit,
		&i.LastCheck,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceIDRef,
		&i.ServiceName,
		&i.ServiceActive,
		&i.Icon,
		&i.ServiceCreatedAt,
		&i.ServiceUpdatedAt,
		&i.HostName,
		&i.LastMessage,
	)
	return i, err
}

const getHostServiceByID = `-- name: GetHostServiceByID :one
SELECT 
    hs.id, hs.host_id, hs.service_id, hs.active, hs.schedule_number,
    hs.schedule_unit, hs.last_check, hs.status, hs.created_at, hs.updated_at,
    COALESCE(s.id, 0) as service_id_ref, 
    COALESCE(s.service_name, '') as service_name, 
    COALESCE(s.active, 0) as service_active, 
    COALESCE(s.icon, '') as icon, 
    COALESCE(s.created_at, hs.created_at) as service_created_at, 
    COALESCE(s.updated_at, hs.updated_at) as service_updated_at, 
    COALESCE(h.host_name, '') as host_name, 
    hs.last_message
FROM host_services hs
LEFT JOIN services s ON (hs.service_id = s.id)
LEFT JOIN hosts h ON (hs.host_id = h.id)
WHERE hs.id = $1
`

type GetHostServiceByIDRow struct {
	ID               int32
	HostID           int32
	ServiceID        int32
	Active           int32
	ScheduleNumber   int32
	ScheduleUnit     string
	LastCheck        time.Time
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ServiceIDRef     int32
	ServiceName      string
	ServiceActive    int32
	Icon             string
	ServiceCreatedAt time.Time
	ServiceUpdatedAt time.Time
	HostName         string
	LastMessage      string
}

func (q *Queries) GetHostServiceByID(ctx context.Context, id int32) (GetHostServiceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getHostServiceByID, id)
	var i GetHostServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ServiceID,
		&i.Active,
		&i.ScheduleNumber,
		&i.ScheduleUnit,
		&i.LastCheck,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceIDRef,
		&i.ServiceName,
		&i.ServiceActive,
		&i.Icon,
		&i.ServiceCreatedAt,
		&i.ServiceUpdatedAt,
		&i.HostName,
		&i.LastMessage,
	)
	return i, err
}

const getHostServicesForHost = `-- name: GetHostServicesForHost :many
SELECT 
    hs.id, hs.host_id, hs.service_id, hs.active, hs.schedule_number, hs.schedule_unit, 
    hs.last_check, hs.status, hs.created_at, hs.updated_at,
    COALESCE(s.id, 0) as service_id_ref, 
    COALESCE(s.service_name, '') as service_name, 
    COALESCE(s.active, 0) as service_active, 
    COALESCE(s.icon, '') as icon, 
    COALESCE(s.created_at, hs.created_at) as service_created_at, 
    COALESCE(s.updated_at, hs.updated_at) as service_updated_at, 
    hs.last_message
FROM host_services hs
LEFT JOIN services s ON (s.id = hs.service_id)
WHERE hs.host_id = $1
ORDER BY s.service_name
`

type GetHostServicesForHostRow struct {
	ID               int32
	HostID           int32
	ServiceID        int32
	Active           int32
	ScheduleNumber   int32
	ScheduleUnit     string
	LastCheck        time.Time
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ServiceIDRef     int32
	ServiceName      string
	ServiceActive    int32
	Icon             string
	ServiceCreatedAt time.Time
	ServiceUpdatedAt time.Time
	LastMessage      string
}

func (q *Queries) GetHostServicesForHost(ctx context.Context, hostID int32) ([]GetHostServicesForHostRow, error) {
	rows, err := q.db.QueryContext(ctx, getHostServicesForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostServicesForHostRow
	for rows.Next() {
		var i GetHostServicesForHostRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ServiceID,
			&i.Active,
			&i.ScheduleNumber,
			&i.ScheduleUnit,
			&i.LastCheck,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceIDRef,
			&i.ServiceName,
			&i.ServiceActive,
			&i.Icon,
			&i.ServiceCreatedAt,
			&i.ServiceUpdatedAt,
			&i.LastMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServicesByStatus = `-- name: GetServicesByStatus :many
SELECT
    hs.id, hs.host_id, hs.service_id, hs.active, hs.schedule_number, hs.schedule_unit,
    hs.last_check, hs.status, hs.created_at, hs.updated_at,
    COALESCE(h.host_name, '') as host_name, 
    COALESCE(s.service_name, '') as service_name, 
    hs.last_message
FROM host_services hs
LEFT JOIN hosts h ON (hs.host_id = h.id)
LEFT JOIN services s ON (hs.service_id = s.id)
WHERE hs.status = $1 AND hs.active = 1
ORDER BY host_name, service_name
`

type GetServicesByStatusRow struct {
	ID             int32
	HostID         int32
	ServiceID      int32
	Active         int32
	ScheduleNumber int32
	ScheduleUnit   string
	LastCheck      time.Time
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HostName       string
	ServiceName    string
	LastMessage    string
}

func (q *Queries) GetServicesByStatus(ctx context.Context, status string) ([]GetServicesByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getServicesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServicesByStatusRow
	for rows.Next() {
		var i GetServicesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ServiceID,
			&i.Active,
			&i.ScheduleNumber,
			&i.ScheduleUnit,
			&i.LastCheck,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostName,
			&i.ServiceName,
			&i.LastMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServicesToMonitor = `-- name: GetServicesToMonitor :many
SELECT 
    hs.id, hs.host_id, hs.service_id, hs.active, hs.schedule_number,
    hs.schedule_unit, hs.last_check, hs.status, hs.created_at, hs.updated_at,
    COALESCE(s.id, 0) as service_id_ref, 
    COALESCE(s.service_name, '') as service_name, 
    COALESCE(s.active, 0) as service_active, 
    COALESCE(s.icon, '') as icon, 
    COALESCE(s.created_at, hs.created_at) as service_created_at, 
    COALESCE(s.updated_at, hs.updated_at) as service_updated_at,
    COALESCE(h.host_name, '') as host_name, 
    hs.last_message
FROM host_services hs
LEFT JOIN services s ON (hs.service_id = s.id)
LEFT JOIN hosts h ON (h.id = hs.host_id)
WHERE h.active = 1 AND hs.active = 1
`

type GetServicesToMonitorRow struct {
	ID               int32
	HostID           int32
	ServiceID        int32
	Active           int32
	ScheduleNumber   int32
	ScheduleUnit     string
	LastCheck        time.Time
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ServiceIDRef     int32
	ServiceName      string
	ServiceActive    int32
	Icon             string
	ServiceCreatedAt time.Time
	ServiceUpdatedAt time.Time
	HostName         string
	LastMessage      string
}

func (q *Queries) GetServicesToMonitor(ctx context.Context) ([]GetServicesToMonitorRow, error) {
	rows, err := q.db.QueryContext(ctx, getServicesToMonitor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServicesToMonitorRow
	for rows.Next() {
		var i GetServicesToMonitorRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ServiceID,
			&i.Active,
			&i.ScheduleNumber,
			&i.ScheduleUnit,
			&i.LastCheck,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceIDRef,
			&i.ServiceName,
			&i.ServiceActive,
			&i.Icon,
			&i.ServiceCreatedAt,
			&i.ServiceUpdatedAt,
			&i.HostName,
			&i.LastMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (host_service_id, event_type, host_id, service_name, host_name, message, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertEventParams struct {
	HostServiceID int32
	EventType     string
	HostID        int32
	ServiceName   string
	HostName      string
	Message       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.HostServiceID,
		arg.EventType,
		arg.HostID,
		arg.ServiceName,
		arg.HostName,
		arg.Message,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertHost = `-- name: InsertHost :one
INSERT INTO hosts (host_name, canonical_name, url, ip, ipv6, location, os, active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertHostParams struct {
	HostName      string
	CanonicalName string
	Url           string
	Ip            string
	Ipv6          string
	Location      string
	Os            string
	Active        int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertHost(ctx context.Context, arg InsertHostParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertHost,
		arg.HostName,
		arg.CanonicalName,
		arg.Url,
		arg.Ip,
		arg.Ipv6,
		arg.Location,
		arg.Os,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertHostServiceDefault = `-- name: InsertHostServiceDefault :exec
INSERT INTO host_services 
    (host_id, service_id, active, schedule_number, schedule_unit, status, created_at, updated_at)
VALUES ($1, $2, 0, 3, 'm', 'pending', $3, $4)
`

type InsertHostServiceDefaultParams struct {
	HostID    int32
	ServiceID int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertHostServiceDefault(ctx context.Context, arg InsertHostServiceDefaultParams) error {
	_, err := q.db.ExecContext(ctx, insertHostServiceDefault,
		arg.HostID,
		arg.ServiceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listServiceIDs = `-- name: ListServiceIDs :many
SELECT id FROM services
`

func (q *Queries) ListServiceIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listServiceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHost = `-- name: UpdateHost :exec
UPDATE hosts 
SET host_name = $1, canonical_name = $2, url = $3, ip = $4, ipv6 = $5, os = $6,
    active = $7, location = $8, updated_at = $9 
WHERE id = $10
`

type UpdateHostParams struct {
	HostName      string
	CanonicalName string
	Url           string
	Ip            string
	Ipv6          string
	Os            string
	Active        int32
	Location      string
	UpdatedAt     time.Time
	ID            int32
}

func (q *Queries) UpdateHost(ctx context.Context, arg UpdateHostParams) error {
	_, err := q.db.ExecContext(ctx, updateHost,
		arg.HostName,
		arg.CanonicalName,
		arg.Url,
		arg.Ip,
		arg.Ipv6,
		arg.Os,
		arg.Active,
		arg.Location,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateHostService = `-- name: UpdateHostService :exec
UPDATE host_services 
SET host_id = $1, service_id = $2, active = $3,
    schedule_number = $4, schedule_unit = $5, 
    last_check = $6, status = $7, updated_at = $8, last_message = $9
WHERE id = $10
`

type UpdateHostServiceParams struct {
	HostID         int32
	ServiceID      int32
	Active         int32
	ScheduleNumber int32
	ScheduleUnit   string
	LastCheck      time.Time
	Status         string
	UpdatedAt      time.Time
	LastMessage    string
	ID             int32
}

func (q *Queries) UpdateHostService(ctx context.Context, arg UpdateHostServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateHostService,
		arg.HostID,
		arg.ServiceID,
		arg.Active,
		arg.ScheduleNumber,
		arg.ScheduleUnit,
		arg.LastCheck,
		arg.Status,
		arg.UpdatedAt,
		arg.LastMessage,
		arg.ID,
	)
	return err
}

const updateHostServiceStatus = `-- name: UpdateHostServiceStatus :exec
UPDATE host_services 
SET active = $1 
WHERE host_id = $2 AND service_id = $3
`

type UpdateHostServiceStatusParams struct {
	Active    int32
	HostID    int32
	ServiceID int32
}

func (q *Queries) UpdateHostServiceStatus(ctx context.Context, arg UpdateHostServiceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateHostServiceStatus, arg.Active, arg.HostID, arg.ServiceID)
	return err
}
