// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Event struct {
	ID            int32
	EventType     string
	HostServiceID int32
	HostID        int32
	ServiceName   string
	HostName      string
	Message       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Host struct {
	ID            int32
	HostName      string
	CanonicalName string
	Url           string
	Ip            string
	Ipv6          string
	Location      string
	Os            string
	Active        int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type HostService struct {
	ID             int32
	HostID         int32
	ServiceID      int32
	Active         int32
	ScheduleNumber int32
	ScheduleUnit   string
	LastCheck      time.Time
	Status         string
	LastMessage    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Service struct {
	ID          int32
	ServiceName string
	Active      int32
	Icon        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
